data_cleaning:
  DEV_DATA_PATH : 'data/raw/Dev_data_to_be_shared.csv'  # Path to the raw data
  VAL_DATA_PATH : 'data/raw/validation_data_to_be_shared.csv'  # Path to the raw validation data

  ENCODING_TECHNIQUE : 'target'  # Encoding technique to be used for categorical features  'target' or 'ordinal'
  
  NULL_PERCENTAGE : 0.25   # features with more than given missing values will be dropped
  VARIANCE_THRESHOLD : 0   # features with less variance than given threshold will be dropped
  IMPUTATION_TECHNIQUE : 'mode'  # Impuation technique to be used for missing values
  KNN_IMPUTER_N_NEIGHBORS : 5    # Number of neighbors to be used for KNN imputation
  TEST_SIZE : 0.2     # Test size for train-test split
  RANDOM_STATE : 42

feature_engineering:

  FEATURE_IMPORTANCE_TECHNIQUE : 'combine'  # Feature importance technique to be used 'combine' or 'fisher' or 'rf' or 'xgb'
  NO_FEATURES : 40

  FEATURE_SELECTION_TECHNIQUE : 'anova'  # Feature selection technique to be used    'anova' or 'backward' or 'autoencoder'
  ANOVA_K : 40  # Number of features to be selected using ANOVA

  # If selection technique is Sequential Backward Selection than hyperparameters of RF model
  SFS_FORWARD : False  # IF False than SFS will be used as SBS
  N_ESTIMATORS : 200
  MAX_DEPTH : 10
  MIN_SAMPLES_SPLIT : 5
  MIN_SAMPLES_LEAF : 2
  MAX_FEATURES : 'sqrt'
  RANDOM_STATE : 42

